### ISSUE TITLE
TLS cert on Heyday server is missing intermediate cert

### ISSUE THREAD

**Issue by oddnoc** [heyday/beam#50]
The installer fails to download or (when manually downloaded) run on certain systems (specifically FreeBSD in my case) because of the missing [SSL CA - G2](https://ssltools.thawte.com/chainTester/webservice/validatecerts/certificate?certKey=issuer.intermediate.cert.48&fileName=thawte%20SSL%20CA%20-%20G2&fileExtension=txt) certificate on your server. See <https://ssltools.thawte.com/checker/views/certCheck.jsp> and enter https://beam.heyday.net.nz/ for details.

Update: the installer downloads but cannot run on Mac OS X (Yosemite 10.10.4).

**Comment by shane-garelja** [comment]
Thanks Fred, all sorted.
