### ISSUE TITLE
pass option to allow rsync to run as root on target

### ISSUE THREAD

**Issue by rsouthgate** [heyday/beam#52]
Using a default AWS EC2 instance and connecting with the ubuntu user I would like to be able to rsync as root so that permissions on target directories can be changed. I think in rsync itself I can pass --rsync-path "sudo rsync" and the ubuntu user would run as root. But can I pass this through the beam options in any way?

**Comment by stecman** [comment]
The command line option `--args <string>` allows passing arbitrary arguments to rsync, but it needs to be passed every time you run beam:

```
beam up something --args="--rsync-path 'sudo rsync'"
```

Alternatively, you could run pre-deployment commands on the server to set the right permissions:

```javascript
{
	// ...
	"commands": [
		{
			"command": "sudo do the thing",
			"location": "target",
			"phase": "pre"
		}
	]
}
```

**Comment by icecaster** [comment]
Allowing to pass rsync params on a per server config would allow this - 
See https://github.com/heyday/beam/issues/53

**Comment by stecman** [comment]
FWIW, in the scenario @rsouthgate mentions, adding a public key to the account you want to deploy as then using that account seems like a better solution (without any other context). I'm hesitant to make it easy to run things as root, since `sudo` is often not the right solution.

**Comment by stecman** [comment]
> so that permissions on target directories can be changed

Seems like this particular issue is addressed by https://github.com/heyday/beam/pull/57, so I'm closing this for now.
