### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by stephecloutier** [heyday/beam#58]
Is it possible to user Beam on windows ? I can't find this information anywhere.

**Comment by stecman** [comment]
Hey @stephecloutier, I'm not aware of anyone who has achieved this, but in theory it should be possible with the recent addition of the [Linux subsystem on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

Beam is essentially a wrapper around a few common Linux/Unix programs. In the default `rsync` mode, it requires:

- `rsync` to transfer files (over ssh)
- `ssh` to run shell commands on remote machines
- `git` to extract a clean copy of what you're deploying from your repository (unless run with `--working-copy`)

The SFTP and FTP modes have fewer dependencies, though they're not as fast or mature as the `rsync` mode. SFTP only requries `git` and the `ssh2` PHP extension (which appears to be available for Windows natively). FTP mode should only require `git`, but it has no SSL support so maybe not advisable to use.

Other issues running natively under Windows are likely to be:

- Unix-style paths everwhere
- Assumptions about where programs live (everything available on PATH)
- ANSI escape sequences (colour and the cursor control used for a progress bar)

@stevie-mayhew was possibly going to have a look it this using Cygwin a few years back, though I'm not sure how far he got.

**Comment by stevie-mayhew** [comment]
We did have this running on Windows. We had to use a custom version of beam with windows style paths set up for cygwin. 

If you're interested I can see if I can dig up the code and see what changes we had to make.

**Comment by stephecloutier** [comment]
Thanks @stecman , I'll try to see what I can do to make it work ! 
@stevie-mayhew I would be interested into seing what changes you made, thanks !

**Comment by zanderwar** [comment]
I'd like to +1 for a windows version, almost had it working in git-bash

```
$ beam up staging
[warn] You're about to sync files between:
[warn] SOURCE: /tmp/beam-4f4206af1a0203f2046271cd92b8ca8d @ origin/staging
[warn] TARGET: vulcan@111.111.111.111:21:~/public_html/subdomains/staging
[info] Determining list of files that will be modified...
[info] Preparing local deploy path
[info] Exporting ref
[error] mkdir(): No such file or directory
```

Obviously failed at making the source dir

**Comment by stecman** [comment]
I've just tested this under the Linux subsystem and it works great (including Bash completion for Beam).

### Installing Beam in the Linux subsystem for Windows

1. Install the Windows 10 Linux subsystem. I followed these instructions to do this:
   1. Open settings
   2. Navigate to "For developers" (Update & Security -> For developers)
   3. Select Developer mode
   4. Open "Turn Windows features on or off" by searching in the start menu or settings app
   5. Tick *Windows Subsystem for Linux (Beta)*, hit OK and wait a while
   6. In your terminal emulator of choice, run `bash.exe`

2. Inside `bash.exe`, set up Beam:
   1. Install required packages:

      ``` sh
      sudo apt-get install php-cli php-ssh2 php-mbstring
      ```
   2.  Install beam per the readme (or from source if you want)
   3. Set up any SSH config, private keys, etc you want to use with Beam

![beam-windows](https://user-images.githubusercontent.com/2230769/36346213-126d8148-149f-11e8-8f99-cac0c3f43aa1.gif)

### Further integration

If you wanted to go a step further to make this accessible in Windows land, `bash.exe` takes a shell script as an argument. If you can alias `beam` to `bash.exe beam.sh` in your Windows shell, where `beam.sh` is the following, you could call it from cygwin/git-bash too.

```sh
/linux/path/to/beam "$@"
```

There are probably other ways to implement this. I'm not particularly familiar with Windows CMD shell features.

![image](https://user-images.githubusercontent.com/2230769/36346260-073cadd4-14a0-11e8-826c-22afab1374ef.png)

### NTFS caveats

Permissions on NTFS volumes always read as `0777`, so you'd want to use `"syncPermissions": false` for all of your server definitions.

**Comment by stevie-mayhew** [comment]
Unfortunately I've lost the code we had for this, but it looks like @stecman has a better option.

If I remember correctly, we simply needed to change the temporary directory and target path extensions so they had a root in "C:/".

**Comment by stephecloutier** [comment]
Thanks @stecman , I've managed to use beam on my Windows PC !
I still get an error when running `beam up live` and I'm not sure I understand why I get it : 

```
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalThrowableError' not found in phar:///usr/local/bin/beam/vendor/symfony/console/Application.php:2
Stack trace:
#0 phar:///usr/local/bin/beam/bin/beam(2): Symfony\Component\Console\Application->run()
#1 /usr/local/bin/beam(4): require('phar:///usr/loc...')
#2 {main}
  thrown in phar:///usr/local/bin/beam/vendor/symfony/console/Application.php on line 2

Fatal error: Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalThrowableError' not found in phar:///usr/local/bin/beam/vendor/symfony/console/Application.php:2
Stack trace:
#0 phar:///usr/local/bin/beam/bin/beam(2): Symfony\Component\Console\Application->run()
#1 /usr/local/bin/beam(4): require('phar:///usr/loc...')
#2 {main}
  thrown in phar:///usr/local/bin/beam/vendor/symfony/console/Application.php on line 2
```

I'll try to find out what is causing it

**Comment by stecman** [comment]
Try run Beam from source, @stephecloutier: clone, `composer install`, `./bin/beam`.

I ran into that too running under php7 - it's because the phar building script doesn't include `vendor/symfony/debug`. Haven't pushed the phar fix up yet.

**Comment by shane-garelja** [comment]
Closing given no further comments.

**Comment by kartikpatel95** [comment]
@shane-garelja will this issue be fixed for php8?
