### ISSUE TITLE
Define private key explicitly

### ISSUE THREAD

**Issue by abstractk** [heyday/beam#59]
I'm not sure if there is way currently to define location for private key used for server authentication. Can you please confirm?

**Comment by shane-garelja** [comment]
I believe you could do that with the --args argument to pass arguments to rsync e.g: 
`beam up live --args='-e "ssh -i ~/.ssh/somekey"'`

**Comment by stecman** [comment]
We let `ssh` to decide how to connect to a host, though it looks like this isn't mentioned anywhere in the docs at the moment.

To specify a particular key for a host, add a definition to your `~/.ssh/config` file:

```
Host example.com
    IdentityFile ~/.ssh/some_private_key
```

You can configure [any ssh client options](http://man7.org/linux/man-pages/man5/ssh_config.5.html) this way. It's typical to have this config set up so you can `ssh somehost` in addition to using Beam:

```
Host somehost somehost.example.com
    HostName 198.51.100.123
    User john
    IdentityFile ~/.ssh/some_private_key
```

**Comment by shane-garelja** [comment]
Yes - that's the correct way, I was assuming the OP wanted something a little more ad-hoc ;)

**Comment by abstractk** [comment]
All good. Thanks guys :)
