### ISSUE TITLE
Beam does not work with PHP8 CLI

### ISSUE THREAD

**Issue by kartikpatel95** [heyday/beam#66]
When running PHP 8.0.8 in the CLI beam will no deploy runs into a error. Downgrading it to PHP7 runs it.

```
Fatal error: Uncaught Error: Class "Symfony\Component\Debug\Exception\FatalThrowableError" not found in phar:///usr/local/bin/beam/vendor/symfony/console/Application.php:2
Stack trace:
#0 phar:///usr/local/bin/beam/bin/beam(2): Symfony\Component\Console\Application->run()
#1 /usr/local/bin/beam(4): require('phar:///usr/loc...')
#2 {main}
  thrown in phar:///usr/local/bin/beam/vendor/symfony/console/Application.php on line 2
```

**Comment by wilr** [comment]
@kartikpatel95 Have you tried the latest version? See https://github.com/heyday/beam/commit/4c50252a76d8f9e2fc1cbf96700aa782d5272885

**Comment by wilr** [comment]
I'm unable to update the version on getbeam.io. In the mean time you'll need to clone this repo and update your beam link to point the the one in this repo https://github.com/heyday/beam/blob/master/bin/beam.
